### ISSUE TITLE
Dear team of NASP

### ISSUE THREAD

**Issue by OrsonMM** [TGenNorth/NASP#15]
I am using the pipeline with 1515 genomes draft (contings), And I have these error 

It works well to begin. But in the file 800 show me:

Traceback (most recent call last):
  File "/usr/local/bin/nasp", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/nasp/nasp.py", line 611, in main
    dispatcher.begin(configuration)
  File "/usr/local/lib/python3.5/dist-packages/nasp/dispatcher.py", line 695, in begin
    (job_id, final_file) = _convert_external_genome(assembly, configuration, index_job_id, reference)
  File "/usr/local/lib/python3.5/dist-packages/nasp/dispatcher.py", line 485, in _convert_external_genome
    job_id = _submit_job(configuration["job_submitter"], command, job_parms, (index_job_id,))
  File "/usr/local/lib/python3.5/dist-packages/nasp/dispatcher.py", line 126, in _submit_job
    total_mem = subprocess.getoutput("free -g | grep Mem: | awk '{ print $2 }'")
  File "/usr/lib/python3.5/subprocess.py", line 824, in getoutput
    return getstatusoutput(cmd)[1]
  File "/usr/lib/python3.5/subprocess.py", line 805, in getstatusoutput
    data = check_output(cmd, shell=True, universal_newlines=True, stderr=STDOUT)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1454, in _execute_child
    errpipe_read, errpipe_write = os.pipe()
OSError: [Errno 24] Too many open files

Please helpme

**Comment by druvus** [comment]
@OrsonMM  In the current session you could extand the allowed file number by this command: `ulimit -n 10000` or some higher number

**Comment by OrsonMM** [comment]
but in what step ? 

I install using pip nasp 

I can view that comand line interact don´t give me the options for select snp call tools or aligment bwa, bowtie or other option. 

It apparently work well but, don´t generate good outputs:

ubuntu@vibrio:~$ nasp
Welcome to NASP version 1.0.0.

Where would you like output files to be written [nasp_results]? Resultados/loplop

Where is the reference fasta file you would like to use? Data/all_vp/reference/GCA_000196095_1_O3K6.fasta

Do you want to check the reference for duplicated regions
and skip SNPs that fall in those regions [Y]? Y

What system do you use for job management (PBS/TORQUE, SLURM, SGE/OGE, and 'none' are currently supported) [PBS]? none

Do you have fasta files for external genomes you wish to include [Y]? Y

Do you have fasta files for external genomes you wish to include [Y]? Data/all_vp/prueba_nasp/
Where are these files located [/home/ubuntu]? Data/all_vp/prueba_nasp/
  Would you like to set advanced NUCmer settings [N]?

Do you have read files you wish to include [Y]? N

Do you have pre-aligned SAM/BAM files you wish to include [N]? N

Do you have pre-called VCFfiles you wish to include [N]?
Would you like to set advanced MatrixGenerator settings [N]?

Do you want to create a master_masked matrix that includes all positions with low-quality positions that failed the covera
total_mem = 188
total_mem = 188
total_mem = 188
total_mem = 188
total_mem = 188
total_mem = 188
total_mem = 188
total_mem = 188

**Comment by DarwinW13** [comment]
Andreas’ answer is correct, but it is not part of the pipeline, that is an operating system command that you need to run before running NASP. The error you got is the operating system telling you you have opened more files at once than it wants to let you, the ulimit -n command will increase that limit for the current session.

BUT, I can also see you may have problems by answering ‘none’ for job management system. That option was provided just as a way to test the pipeline or to run with with small (10-20 genome) datasets. For 1515 genomes its going to take a very long time to get through them without a job manager like SLURM running on a cluster (which is how NASP was designed to be run) Although, the fact that you got to the ‘Too many open files’ error at all is a good sign that you might still be okay after increasing the limit. Certainly try it out, but I can make no guarantees without using a job manager.

Darrin

---
Darrin Lemmer
Bioinformatics Lead
TGen North
dlemmer@tgen.org

On October 9, 2018 at 9:41:36 AM, Orson (notifications@github.com) wrote:

but in what step ?

I install using pip nasp

I can view that comand line interact don´t give me the options for select snp call tools or aligment bwa, bowtie or other option.

It apparently work well but, don´t generate good outputs:

ubuntu@vibrio:~$ nasp
Welcome to NASP version 1.0.0.

Where would you like output files to be written [nasp_results]? Resultados/loplop

Where is the reference fasta file you would like to use? Data/all_vp/reference/GCA_000196095_1_O3K6.fasta

Do you want to check the reference for duplicated regions
and skip SNPs that fall in those regions [Y]? Y

What system do you use for job management (PBS/TORQUE, SLURM, SGE/OGE, and 'none' are currently supported) [PBS]? none

Do you have fasta files for external genomes you wish to include [Y]? Y

Do you have fasta files for external genomes you wish to include [Y]? Data/all_vp/prueba_nasp/
Where are these files located [/home/ubuntu]? Data/all_vp/prueba_nasp/
Would you like to set advanced NUCmer settings [N]?

Do you have read files you wish to include [Y]? N

Do you have pre-aligned SAM/BAM files you wish to include [N]? N

Do you have pre-called VCFfiles you wish to include [N]?
Would you like to set advanced MatrixGenerator settings [N]?

Do you want to create a master_masked matrix that includes all positions with low-quality positions that failed the covera
total_mem = 188
total_mem = 188
total_mem = 188
total_mem = 188
total_mem = 188
total_mem = 188
total_mem = 188
total_mem = 188

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
-- 










*This electronic message is intended to be for the use only of 
the named recipient, and may contain information that is confidential or 
privileged, including patient health information. If you are not the 
intended recipient, you are hereby notified that any disclosure, copying, 
distribution or use of the contents of this message is strictly prohibited. 
If you have received this message in error or are not the named recipient, 
please notify us immediately by contacting the sender at the electronic 
mail address noted above, and delete and destroy all copies of this 
message. Thank you.*
