### ISSUE TITLE
error in missingdata.tsv

### ISSUE THREAD

**Issue by maziz2** [TGenNorth/NASP#6]
Hi Jay

It looks like the counts #NXdegen column are incorrect. I find 'N' in my calls but the #NXdegen count is 0. i am attaching my matrix. As an example please look at rows 13,14,15 (positions: 810,831,843)

thanks

Maliha
[missingdata.tsv.zip](https://github.com/TGenNorth/NASP/files/190123/missingdata.tsv.zip)

**Comment by corburn** [comment]
Hello Maliha,

The positions you are referring to failed your minimum proportion threshold. The output file you provided masks positions that failed either the coverage or proportion threshold with an N. The #NXdegen column was not incremented because there were no N, X, or degen calls at those positions in the input VCF/FASTA files.

Kind regards,
Jason Travis

**Comment by maziz2** [comment]
I am so confused! the manual (http://tgennorth.github.io/NASP/usage.html#matrix) says
Missing Data	:  Positions that passed the General Stats quality_breadth filter
quality_breadth	Number of positions called A/C/G/T and passed all filters for all samples.

so missing data is **not** Positions that passed the General Stats quality_breadth filter?

**Comment by corburn** [comment]
Hello Maliha,

Missing data could be summarized as the Best SNP matrix without the constraint that SNPs be present in all samples. Positions that failed the user's coverage/proportion threshold are masked with an N.
